-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
--
-- Intentionally empty: LazyVim's defaults are enough here. The ESLint-fix-on-save
-- autocmd for i18n JSON that used to live in this file was specific to one repo's
-- lint rules, so it moved into that repo's `.nvim.lua` (enabled by `vim.o.exrc`
-- in config/options.lua) rather than running on every machine and every project.
