blacklist = ["scratch"]

[[session]]
name = "dotfiles"
path = "~/dotfiles"

[[session]]
name = "portal"
path = "~/Desktop/into.care/portal"

[[session]]
name = "intocare"
path = "~/Desktop/into.care/intocare"
